---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-nestjs-postgresql-100-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab-gitlabapps.sandbox-m2.ll9k.p1.openshiftapps.com/erlisb/rhdh-nestjs-postgresql-100-gitops.git
